version: '3'

services:
  feature-db:
    image: postgres:16.3-alpine3.20
    container_name: feature-db
    ports:
      - '5432:5432'
    volumes:
      - feature-db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=feature
      - POSTGRES_PASSWORD=feature
      - POSTGRES_DB=feature

volumes:
  feature-db:
